version: '3.3'

volumes:
  pg_data:
  staticfiles:

services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h $DB_HOST -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: backend/.
    env_file: .env
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: nginx/.
    ports:
      - "80:80"
    volumes:
      - staticfiles:/staticfiles/
    depends_on:
      - backend