# Generated by Django 4.2.13 on 2024-06-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('1 месяц', '1 месяц'), ('6 месяцев', '6 месяцев'), ('12 месяцев', '12 месяцев')], max_length=20, verbose_name='Длительность подписки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
