# Generated by Django 4.2.13 on 2024-06-22 13:22

import arts.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвета",
            },
        ),
        migrations.CreateModel(
            name="Orientation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ориентация",
                "verbose_name_plural": "Ориентации",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер",
                "verbose_name_plural": "Размеры",
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стиль",
                "verbose_name_plural": "Стили",
            },
        ),
        migrations.CreateModel(
            name="Art",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        max_length=255, verbose_name="Автор объекта"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="arts/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "appraisal_price",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Оценочная цена",
                    ),
                ),
                (
                    "year",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            arts.validators.validate_year,
                        ],
                        verbose_name="Год создания объекта",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="arts.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="arts.color",
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "orientation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="arts.orientation",
                        verbose_name="Ориентация",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="arts.size",
                        verbose_name="Размер",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="arts.style",
                        verbose_name="Стиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Арт-объект",
                "verbose_name_plural": "Арт-объекты",
                "default_related_name": "arts",
            },
        ),
    ]
