# Generated by Django 4.2.13 on 2024-07-01 10:06

import arts.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'default_related_name': 'appraisals',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Автор объекта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/%Y/%m/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('gender', models.CharField(choices=[('М', 'Male'), ('Ж', 'Female')], max_length=6, verbose_name='Пол')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
            ],
            options={
                'verbose_name': 'Автор картины',
                'verbose_name_plural': 'Авторы картин',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='events/%Y/', verbose_name='Фото')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('begin', models.DateField(verbose_name='Начало события')),
                ('end', models.DateField(verbose_name='Конец события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['begin', 'end'],
            },
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Ориентация',
                'verbose_name_plural': 'Ориентации',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Показ',
                'verbose_name_plural': 'Показы',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='arts/%Y/%m/%d/', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
                ('appraisal_price', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Оценочная цена')),
                ('year', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(100), arts.validators.validate_year], verbose_name='Год создания объекта')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('sold', models.BooleanField(default=False, verbose_name='Объект продан')),
                ('popular', models.PositiveSmallIntegerField(default=0, verbose_name='Популярность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arts.author', verbose_name='Автор объекта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arts.category', verbose_name='Категория')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arts.color', verbose_name='Цвет')),
                ('group_shows', models.ManyToManyField(blank=True, related_name='group_arts', to='arts.show')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arts.orientation', verbose_name='Ориентация')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arts.size', verbose_name='Размер')),
                ('solo_shows', models.ManyToManyField(blank=True, related_name='solo_arts', to='arts.show')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arts.style', verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Арт-объект',
                'verbose_name_plural': 'Арт-объекты',
                'default_related_name': 'arts',
            },
        ),
    ]
