# Generated by Django 4.2.13 on 2024-07-01 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.art'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='appraisal',
            constraint=models.UniqueConstraint(fields=('user', 'art'), name='unique_art_user'),
        ),
    ]
