# Generated by Django 4.2.13 on 2024-06-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="events/%Y/", verbose_name="Фото"
                    ),
                ),
                ("begin", models.DateField(verbose_name="Начало события")),
                ("end", models.DateField(verbose_name="Конец события")),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
    ]
