# Generated by Django 4.2.13 on 2024-06-24 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='art',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arts.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='art',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arts.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='art',
            name='orientation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arts.orientation', verbose_name='Ориентация'),
        ),
        migrations.AddField(
            model_name='art',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arts.size', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='art',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arts.style', verbose_name='Стиль'),
        ),
    ]
