# Generated by Django 4.2.13 on 2024-06-23 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0002_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["begin", "end"],
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
    ]
