# Generated by Django 4.2.13 on 2024-06-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0003_event_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="link",
            field=models.URLField(verbose_name="Ссылка"),
        ),
    ]
