# Generated by Django 4.2.13 on 2024-06-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0004_alter_event_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Автор объекта"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор картины",
                "verbose_name_plural": "Авторы картин",
            },
        ),
        migrations.RemoveField(
            model_name="art",
            name="author_name",
        ),
        migrations.AddField(
            model_name="art",
            name="art_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="arts.author",
                verbose_name="Автор объекта",
            ),
        ),
    ]
