# Generated by Django 4.2.13 on 2024-06-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0005_author_remove_art_author_name_art_art_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="art_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="arts.author",
                verbose_name="Автор объекта",
            ),
        ),
    ]
