# Generated by Django 4.2.13 on 2024-06-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0006_alter_art_art_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="popular",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Популярность"
            ),
        ),
    ]
