# Generated by Django 4.2.13 on 2024-06-29 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("arts", "0007_art_popular"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="art",
            name="art_author",
        ),
        migrations.AddField(
            model_name="art",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="art",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="arts.author",
                verbose_name="Автор объекта",
            ),
        ),
    ]
