# Generated by Django 4.2.13 on 2024-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0009_alter_art_author_alter_art_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Страна"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="death_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата смерти"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="gender",
            field=models.CharField(
                choices=[("М", "Male"), ("Ж", "Female")],
                default="М",
                max_length=6,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="birth_date",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
    ]
