# Generated by Django 4.2.13 on 2024-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "arts",
            "0010_author_country_author_death_date_author_gender_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="country",
            field=models.CharField(max_length=50, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="author",
            name="gender",
            field=models.CharField(
                choices=[("М", "Male"), ("Ж", "Female")],
                max_length=6,
                verbose_name="Пол",
            ),
        ),
    ]
