# Generated by Django 4.2.13 on 2024-06-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0011_alter_author_country_alter_author_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Показ",
                "verbose_name_plural": "Показы",
            },
        ),
        migrations.AddField(
            model_name="art",
            name="group_shows",
            field=models.ManyToManyField(
                blank=True, related_name="group_arts", to="arts.show"
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="solo_shows",
            field=models.ManyToManyField(
                blank=True, related_name="solo_arts", to="arts.show"
            ),
        ),
    ]
