# Generated by Django 4.2.13 on 2024-06-30 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0013_appraisal_appraisal_unique_art_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appraisal",
            options={
                "default_related_name": "appraisals",
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
            },
        ),
    ]
