# Generated by Django 4.2.13 on 2024-06-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0014_alter_appraisal_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
    ]
