# Generated by Django 4.2.13 on 2024-06-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0015_art_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="artists/%Y/%m/",
                verbose_name="Фото",
            ),
        ),
    ]
