# Generated by Django 4.2.13 on 2024-06-20 20:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=12, region=None, unique=True, verbose_name="Номер телефон"
            ),
        ),
    ]
